### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by ssd-ls-a** [chemnet-io/coconutKG#12]
- image schema

**Comment by looooph** [comment]
Can @edgardmarx provide some examples(We looked at some when we initially talked about the issue) on how a "good version for a paper" - graph, especially in terms of complexity looks like.

**Comment by looooph** [comment]
Model of the Schema for the paper can be found in https://github.com/chemnet-io/coconut-schema . Text coming soon.

**Comment by looooph** [comment]
Schema has been updated to current version in terms of papergraphic and can be checked out here https://github.com/chemnet-io/coconut-schema/blob/main/schema1_0_0.svg

Texts has been added/modified to the new ontology aswell.

**Comment by looooph** [comment]
Closed for now, as we focus on the nubbe-paper for now.
