### ISSUE TITLE
Some  links are pointing to the wrong path i.e. ./coco/* where it should be ./*

### ISSUE THREAD

**Issue by edgardmarx** [chemnet-io/coconutKG#16]
Some paths on the web page have the wrong prefix:

`http://coconut-kg.aksw.org/coco/ontology/index.html`

and

`http://coconut-kg.aksw.org/coco/dataset/index.html`

the coco should be removed i.e.

`http://coconut-kg.aksw.org/dataset/index.html` instead of `http://coconut-kg.aksw.org/coco/dataset/index.html`

**Comment by looooph** [comment]
All done, /coco/ is no more
