### ISSUE TITLE
CSS broken in query interface

### ISSUE THREAD

**Issue by edgardmarx** [chemnet-io/coconutKG#17]
The CSS is broken at the query interface which does not allow the user to visualize properly the query, see the image attached.
<img width="901" alt="Screenshot 2022-10-09 at 14 48 23" src="https://user-images.githubusercontent.com/4638593/194757744-87cefe2b-6565-4576-befb-959d32e0703d.png">

**Comment by looooph** [comment]
![image](https://user-images.githubusercontent.com/40400000/195672540-848ecba8-a8f3-4e66-a1e0-7cca59d5d77e.png)

Funny thing, if you change the height, it fixes itself. I'll have look at this tomorrow, the yasgui.css file is a complete mess.

**Comment by looooph** [comment]
I did things I am not proud of, but it works
