### ISSUE TITLE
solve CORS problem

### ISSUE THREAD

**Issue by ssd-ls-a** [chemnet-io/coconutKG#19]

**Comment by looooph** [comment]
The CORS issue only appears in specific browser(versions even), namely Firefox, Safari.
Source of problem currently unknown, as CORS is activated on the Virtuoso-Service

**Comment by looooph** [comment]
I have found the problem, it has always just been a yasgui feature here (saving the last made query, it's result and... the endpoint.)

Which in my and Stefans case was a early Version of the /query/ page which had an endpoint set before we decided on the actual domain.
